# Generated by Django 5.0.3 on 2024-10-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estante.livro')),
            ],
        ),
    ]
